version: '3.8'
services:
  postgres:
    container_name: ${DB_NAME:-db}
    image: postgres:latest
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/posgresql/data
    restart: unless-stopped
    networks:
      - postgres

  back:
    container_name: back
    image: node:lts-alpine
    depends_on:
      - postgres
    ports: 
      - "${BACK_PORT:-5000}:${BACK_PORT:-5000}"
      - "5555:5555"
    restart: always
    command: "tail -f"
    # command: /bin/sh -c "apk add bash; npm install; npm run studio ; npm run start:dev"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
        - "./back:/app"
    working_dir: /app
    networks:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  postgres:
    driver: bridge